/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountPlan {
    #[serde(rename = "maxUserCount", skip_serializing_if = "Option::is_none")]
    pub max_user_count: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "isYearly", skip_serializing_if = "Option::is_none")]
    pub is_yearly: Option<bool>,
}

impl AccountPlan {
    pub fn new() -> AccountPlan {
        AccountPlan {
            max_user_count: None,
            name: None,
            is_yearly: None,
        }
    }
}


