/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddResponderToAlertPayloadAllOf {
    #[serde(rename = "responder")]
    pub responder: crate::models::Recipient,
}

impl AddResponderToAlertPayloadAllOf {
    pub fn new(responder: crate::models::Recipient) -> AddResponderToAlertPayloadAllOf {
        AddResponderToAlertPayloadAllOf {
            responder,
        }
    }
}


