/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddTagsToAlertPayloadAllOf {
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
}

impl AddTagsToAlertPayloadAllOf {
    pub fn new(tags: Vec<String>) -> AddTagsToAlertPayloadAllOf {
        AddTagsToAlertPayloadAllOf {
            tags,
        }
    }
}


