/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddDetailsToAlertPayloadAllOf {
    /// Key-value pairs to add as custom property into alert.
    #[serde(rename = "details")]
    pub details: ::std::collections::HashMap<String, String>,
}

impl AddDetailsToAlertPayloadAllOf {
    pub fn new(details: ::std::collections::HashMap<String, String>) -> AddDetailsToAlertPayloadAllOf {
        AddDetailsToAlertPayloadAllOf {
            details,
        }
    }
}


