/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddTeamToAlertPayloadAllOf {
    #[serde(rename = "team")]
    pub team: crate::models::TeamRecipient,
}

impl AddTeamToAlertPayloadAllOf {
    pub fn new(team: crate::models::TeamRecipient) -> AddTeamToAlertPayloadAllOf {
        AddTeamToAlertPayloadAllOf {
            team,
        }
    }
}


