/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertReport {
    #[serde(rename = "ackTime", skip_serializing_if = "Option::is_none")]
    pub ack_time: Option<i64>,
    #[serde(rename = "closeTime", skip_serializing_if = "Option::is_none")]
    pub close_time: Option<i64>,
    #[serde(rename = "acknowledgedBy", skip_serializing_if = "Option::is_none")]
    pub acknowledged_by: Option<String>,
    #[serde(rename = "closedBy", skip_serializing_if = "Option::is_none")]
    pub closed_by: Option<String>,
}

impl AlertReport {
    pub fn new() -> AlertReport {
        AlertReport {
            ack_time: None,
            close_time: None,
            acknowledged_by: None,
            closed_by: None,
        }
    }
}


