/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertRequestStatus {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "processedAt", skip_serializing_if = "Option::is_none")]
    pub processed_at: Option<chrono::DateTime<chrono::offset::Utc>>,
    #[serde(rename = "integrationId", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<String>,
    #[serde(rename = "isSuccess", skip_serializing_if = "Option::is_none")]
    pub is_success: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "alertId", skip_serializing_if = "Option::is_none")]
    pub alert_id: Option<String>,
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
}

impl AlertRequestStatus {
    pub fn new() -> AlertRequestStatus {
        AlertRequestStatus {
            action: None,
            processed_at: None,
            integration_id: None,
            is_success: None,
            status: None,
            alert_id: None,
            alias: None,
        }
    }
}


