/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models::recipient::Type;

/// AllRecipient : All recipient



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllRecipient {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl AllRecipient {
    /// All recipient
    pub fn new(_type: Type) -> AllRecipient {
        AllRecipient {
            id: None,
        }
    }
}


