/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignAlertPayloadAllOf {
    #[serde(rename = "owner")]
    pub owner: crate::models::UserRecipient,
}

impl AssignAlertPayloadAllOf {
    pub fn new(owner: crate::models::UserRecipient) -> AssignAlertPayloadAllOf {
        AssignAlertPayloadAllOf {
            owner,
        }
    }
}


