/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseResponseWithExpandableAllOf {
    #[serde(rename = "expandable", skip_serializing_if = "Option::is_none")]
    pub expandable: Option<Vec<String>>,
}

impl BaseResponseWithExpandableAllOf {
    pub fn new() -> BaseResponseWithExpandableAllOf {
        BaseResponseWithExpandableAllOf {
            expandable: None,
        }
    }
}


