/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseIncident {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tinyId", skip_serializing_if = "Option::is_none")]
    pub tiny_id: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "isSeen", skip_serializing_if = "Option::is_none")]
    pub is_seen: Option<bool>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    #[serde(rename = "responders", skip_serializing_if = "Option::is_none")]
    pub responders: Option<Vec<crate::models::Responder>>,
    #[serde(rename = "ownerTeam", skip_serializing_if = "Option::is_none")]
    pub owner_team: Option<String>,
    /// Map of key-value pairs to use as custom properties of the incident
    #[serde(rename = "extraProperties", skip_serializing_if = "Option::is_none")]
    pub extra_properties: Option<::std::collections::HashMap<String, String>>,
}

impl BaseIncident {
    pub fn new(id: String) -> BaseIncident {
        BaseIncident {
            id,
            tiny_id: None,
            message: None,
            status: None,
            is_seen: None,
            tags: None,
            created_at: None,
            updated_at: None,
            source: None,
            owner: None,
            priority: None,
            responders: None,
            owner_team: None,
            extra_properties: None,
        }
    }
}


