/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloseIncidentPayload {
    /// Additional note that will be included with the incident
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl CloseIncidentPayload {
    pub fn new() -> CloseIncidentPayload {
        CloseIncidentPayload {
            note: None,
        }
    }
}


