/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateHeartbeatPayloadAllOfOwnerTeam : Owner team of the heartbeat, consisting id and/or name of the owner team



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateHeartbeatPayloadAllOfOwnerTeam {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl CreateHeartbeatPayloadAllOfOwnerTeam {
    /// Owner team of the heartbeat, consisting id and/or name of the owner team
    pub fn new() -> CreateHeartbeatPayloadAllOfOwnerTeam {
        CreateHeartbeatPayloadAllOfOwnerTeam {
            name: None,
            id: None,
        }
    }
}


