/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCountAlertsResponseAllOf {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<crate::models::GetCountAlertsResponseAllOfData>,
}

impl GetCountAlertsResponseAllOf {
    pub fn new() -> GetCountAlertsResponseAllOf {
        GetCountAlertsResponseAllOf {
            data: None,
        }
    }
}


