/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncidentRequestStatus {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "processedAt", skip_serializing_if = "Option::is_none")]
    pub processed_at: Option<String>,
    #[serde(rename = "integrationId", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<String>,
    #[serde(rename = "isSuccess", skip_serializing_if = "Option::is_none")]
    pub is_success: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "incidentId", skip_serializing_if = "Option::is_none")]
    pub incident_id: Option<String>,
}

impl IncidentRequestStatus {
    pub fn new() -> IncidentRequestStatus {
        IncidentRequestStatus {
            success: None,
            action: None,
            processed_at: None,
            integration_id: None,
            is_success: None,
            status: None,
            incident_id: None,
        }
    }
}


