/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListHeartbeatResponseAllOfData {
    #[serde(rename = "heartbeats", skip_serializing_if = "Option::is_none")]
    pub heartbeats: Option<Vec<crate::models::Heartbeat>>,
}

impl ListHeartbeatResponseAllOfData {
    pub fn new() -> ListHeartbeatResponseAllOfData {
        ListHeartbeatResponseAllOfData {
            heartbeats: None,
        }
    }
}


