/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models::filter::Type;

/// MatchAllConditions : Match all conditions filter



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchAllConditions {
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::Condition>>,
}

impl MatchAllConditions {
    /// Match all conditions filter
    pub fn new(_type: Type) -> MatchAllConditions {
        MatchAllConditions {
            conditions: None,
        }
    }
}


