/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models::filter::Type;

/// MatchAll : Match all filter



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchAll {
}

impl MatchAll {
    /// Match all filter
    pub fn new(_type: Type) -> MatchAll {
        MatchAll {
        }
    }
}


