/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchAnyConditionAllOf {
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::Condition>>,
}

impl MatchAnyConditionAllOf {
    pub fn new() -> MatchAnyConditionAllOf {
        MatchAnyConditionAllOf {
            conditions: None,
        }
    }
}


