/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnoozeAlertPayloadAllOf {
    /// Date and time that snooze will lose effect
    #[serde(rename = "endTime")]
    pub end_time: chrono::DateTime<chrono::offset::Utc>,
}

impl SnoozeAlertPayloadAllOf {
    pub fn new(end_time: chrono::DateTime<chrono::offset::Utc>) -> SnoozeAlertPayloadAllOf {
        SnoozeAlertPayloadAllOf {
            end_time,
        }
    }
}


