/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TimeRestrictionInterval {
    #[serde(rename="time-of-day")]
    TimeOfDayRestrictionInterval {
        #[serde(rename = "restriction", skip_serializing_if = "Option::is_none")]
        restriction: Option<crate::models::TimeOfDayRestriction>,
    },
    #[serde(rename="weekday-and-time-of-day")]
    WeekdayTimeRestrictionInterval {
        #[serde(rename = "restrictions", skip_serializing_if = "Option::is_none")]
        restrictions: Option<Vec<crate::models::WeekdayTimeRestriction>>,
    },
}



/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "weekday-and-time-of-day")]
    WeekdayAndTimeOfDay,
    #[serde(rename = "time-of-day")]
    TimeOfDay,
}

