/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeOfDayRestriction {
    #[serde(rename = "startHour", skip_serializing_if = "Option::is_none")]
    pub start_hour: Option<i32>,
    #[serde(rename = "startMin", skip_serializing_if = "Option::is_none")]
    pub start_min: Option<i32>,
    #[serde(rename = "endHour", skip_serializing_if = "Option::is_none")]
    pub end_hour: Option<i32>,
    #[serde(rename = "endMin", skip_serializing_if = "Option::is_none")]
    pub end_min: Option<i32>,
}

impl TimeOfDayRestriction {
    pub fn new() -> TimeOfDayRestriction {
        TimeOfDayRestriction {
            start_hour: None,
            start_min: None,
            end_hour: None,
            end_min: None,
        }
    }
}


