/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAlertMessagePayload {
    /// Message of the alert
    #[serde(rename = "message")]
    pub message: String,
}

impl UpdateAlertMessagePayload {
    pub fn new(message: String) -> UpdateAlertMessagePayload {
        UpdateAlertMessagePayload {
            message,
        }
    }
}


