/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAlertDescriptionPayload {
    /// Description of the alert
    #[serde(rename = "description")]
    pub description: String,
}

impl UpdateAlertDescriptionPayload {
    pub fn new(description: String) -> UpdateAlertDescriptionPayload {
        UpdateAlertDescriptionPayload {
            description,
        }
    }
}


