/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models::recipient::Type;

/// UserRecipient : User recipient



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserRecipient {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl UserRecipient {
    /// User recipient
    pub fn new(_type: Type) -> UserRecipient {
        UserRecipient {
            id: None,
            username: None,
        }
    }
}


