/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeekdayTimeRestrictionIntervalAllOf {
    #[serde(rename = "restrictions", skip_serializing_if = "Option::is_none")]
    pub restrictions: Option<Vec<crate::models::WeekdayTimeRestriction>>,
}

impl WeekdayTimeRestrictionIntervalAllOf {
    pub fn new() -> WeekdayTimeRestrictionIntervalAllOf {
        WeekdayTimeRestrictionIntervalAllOf {
            restrictions: None,
        }
    }
}


