/*
 * Python SDK for Opsgenie REST API
 *
 * Python SDK for Opsgenie REST API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@opsgenie.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models::time_restriction_interval::Type;

/// WeekdayTimeRestrictionInterval : Weekday time restriction interval



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeekdayTimeRestrictionInterval {
    #[serde(rename = "restrictions", skip_serializing_if = "Option::is_none")]
    pub restrictions: Option<Vec<crate::models::WeekdayTimeRestriction>>,
}

impl WeekdayTimeRestrictionInterval {
    /// Weekday time restriction interval
    pub fn new(_type: Type) -> WeekdayTimeRestrictionInterval {
        WeekdayTimeRestrictionInterval {
            restrictions: None,
        }
    }
}


